coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 2%

ignore:
  - "tests/"
  - "test/"
  - "*.test.ts"
  - "*.spec.ts"
  - "coverage/"
  - "dist/"
  - "build/"
  - "docs/"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false